// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pkg/api/order.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CartServiceCommanderClient is the client API for CartServiceCommander service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartServiceCommanderClient interface {
	AddCartItem(ctx context.Context, in *CartItem, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCartItem(ctx context.Context, in *CartItem, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cartServiceCommanderClient struct {
	cc grpc.ClientConnInterface
}

func NewCartServiceCommanderClient(cc grpc.ClientConnInterface) CartServiceCommanderClient {
	return &cartServiceCommanderClient{cc}
}

func (c *cartServiceCommanderClient) AddCartItem(ctx context.Context, in *CartItem, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/github.com.sorohimm.uacs_store.CartServiceCommander/AddCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceCommanderClient) DeleteCartItem(ctx context.Context, in *CartItem, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/github.com.sorohimm.uacs_store.CartServiceCommander/DeleteCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceCommanderServer is the server API for CartServiceCommander service.
// All implementations must embed UnimplementedCartServiceCommanderServer
// for forward compatibility
type CartServiceCommanderServer interface {
	AddCartItem(context.Context, *CartItem) (*emptypb.Empty, error)
	DeleteCartItem(context.Context, *CartItem) (*emptypb.Empty, error)
	mustEmbedUnimplementedCartServiceCommanderServer()
}

// UnimplementedCartServiceCommanderServer must be embedded to have forward compatible implementations.
type UnimplementedCartServiceCommanderServer struct {
}

func (UnimplementedCartServiceCommanderServer) AddCartItem(context.Context, *CartItem) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCartItem not implemented")
}
func (UnimplementedCartServiceCommanderServer) DeleteCartItem(context.Context, *CartItem) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCartItem not implemented")
}
func (UnimplementedCartServiceCommanderServer) mustEmbedUnimplementedCartServiceCommanderServer() {}

// UnsafeCartServiceCommanderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServiceCommanderServer will
// result in compilation errors.
type UnsafeCartServiceCommanderServer interface {
	mustEmbedUnimplementedCartServiceCommanderServer()
}

func RegisterCartServiceCommanderServer(s grpc.ServiceRegistrar, srv CartServiceCommanderServer) {
	s.RegisterService(&CartServiceCommander_ServiceDesc, srv)
}

func _CartServiceCommander_AddCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceCommanderServer).AddCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.sorohimm.uacs_store.CartServiceCommander/AddCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceCommanderServer).AddCartItem(ctx, req.(*CartItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartServiceCommander_DeleteCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceCommanderServer).DeleteCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.sorohimm.uacs_store.CartServiceCommander/DeleteCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceCommanderServer).DeleteCartItem(ctx, req.(*CartItem))
	}
	return interceptor(ctx, in, info, handler)
}

// CartServiceCommander_ServiceDesc is the grpc.ServiceDesc for CartServiceCommander service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartServiceCommander_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.sorohimm.uacs_store.CartServiceCommander",
	HandlerType: (*CartServiceCommanderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCartItem",
			Handler:    _CartServiceCommander_AddCartItem_Handler,
		},
		{
			MethodName: "DeleteCartItem",
			Handler:    _CartServiceCommander_DeleteCartItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/order.proto",
}

// OrderServiceCommanderClient is the client API for OrderServiceCommander service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceCommanderClient interface {
	SubmitOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type orderServiceCommanderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceCommanderClient(cc grpc.ClientConnInterface) OrderServiceCommanderClient {
	return &orderServiceCommanderClient{cc}
}

func (c *orderServiceCommanderClient) SubmitOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/github.com.sorohimm.uacs_store.OrderServiceCommander/SubmitOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceCommanderServer is the server API for OrderServiceCommander service.
// All implementations must embed UnimplementedOrderServiceCommanderServer
// for forward compatibility
type OrderServiceCommanderServer interface {
	SubmitOrder(context.Context, *Order) (*emptypb.Empty, error)
	mustEmbedUnimplementedOrderServiceCommanderServer()
}

// UnimplementedOrderServiceCommanderServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceCommanderServer struct {
}

func (UnimplementedOrderServiceCommanderServer) SubmitOrder(context.Context, *Order) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedOrderServiceCommanderServer) mustEmbedUnimplementedOrderServiceCommanderServer() {}

// UnsafeOrderServiceCommanderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceCommanderServer will
// result in compilation errors.
type UnsafeOrderServiceCommanderServer interface {
	mustEmbedUnimplementedOrderServiceCommanderServer()
}

func RegisterOrderServiceCommanderServer(s grpc.ServiceRegistrar, srv OrderServiceCommanderServer) {
	s.RegisterService(&OrderServiceCommander_ServiceDesc, srv)
}

func _OrderServiceCommander_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceCommanderServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.sorohimm.uacs_store.OrderServiceCommander/SubmitOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceCommanderServer).SubmitOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderServiceCommander_ServiceDesc is the grpc.ServiceDesc for OrderServiceCommander service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderServiceCommander_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.sorohimm.uacs_store.OrderServiceCommander",
	HandlerType: (*OrderServiceCommanderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _OrderServiceCommander_SubmitOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/order.proto",
}
