// Code generated by MockGen. DO NOT EDIT.
// Source: category-handler.go

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	category "github.com/sorohimm/uacs-store-back/internal/storage/postgres/api/category"
	api "github.com/sorohimm/uacs-store-back/pkg/api"
)

// MockCategoryCommanderHandler is a mock of CategoryCommanderHandler interface.
type MockCategoryCommanderHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryCommanderHandlerMockRecorder
}

// MockCategoryCommanderHandlerMockRecorder is the mock recorder for MockCategoryCommanderHandler.
type MockCategoryCommanderHandlerMockRecorder struct {
	mock *MockCategoryCommanderHandler
}

// NewMockCategoryCommanderHandler creates a new mock instance.
func NewMockCategoryCommanderHandler(ctrl *gomock.Controller) *MockCategoryCommanderHandler {
	mock := &MockCategoryCommanderHandler{ctrl: ctrl}
	mock.recorder = &MockCategoryCommanderHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryCommanderHandler) EXPECT() *MockCategoryCommanderHandlerMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCategoryCommanderHandler) CreateCategory(ctx context.Context, req *api.CreateCategoryRequest) (*category.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, req)
	ret0, _ := ret[0].(*category.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCategoryCommanderHandlerMockRecorder) CreateCategory(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCategoryCommanderHandler)(nil).CreateCategory), ctx, req)
}
